github/workflows: update main master build to use check-if-release script

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -16,104 +16,141 @@ jobs:
       CI: true
       NODE_OPTIONS: --max-old-space-size=4096
 
+    outputs:
+      needs_release: ${{ steps.release_check.outputs.needs_release }}
+
     steps:
       - uses: actions/checkout@v2
-      - name: fetch branch master
-        run: git fetch origin master
-
-      # Beginning of yarn setup, keep in sync between all workflows.
-      # TODO(Rugvip): move this to composite action once all features we use are supported
-      - name: use node.js ${{ matrix.node-version }}
-        uses: actions/setup-node@v1
         with:
-          node-version: ${{ matrix.node-version }}
-          registry-url: https://registry.npmjs.org/ # Needed for auth
+          fetch-depth: 60
 
-      # Cache every node_modules folder inside the monorepo
-      - name: cache all node_modules
-        id: cache-modules
-        uses: actions/cache@v2
-        with:
-          path: '**/node_modules'
-          # We use both yarn.lock and package.json as cache keys to ensure that
-          # changes to local monorepo packages bust the cache.
-          key: ${{ runner.os }}-v${{ matrix.node-version }}-node_modules-${{ hashFiles('yarn.lock', '**/package.json') }}
+      # - name: fetch branch master
+      #   run: git fetch origin master
 
-      # If we get a cache hit for node_modules, there's no need to bring in the global
-      # yarn cache or run yarn install, as all dependencies will be installed already.
+      - name: Wat 1
+        run: git diff --name-only 619ef5978c3fbfa7c9d6a65c835e1e87dbcec55e '{packages,plugins}/*/package.json'
 
-      - name: find location of global yarn cache
-        id: yarn-cache
-        if: steps.cache-modules.outputs.cache-hit != 'true'
-        run: echo "::set-output name=dir::$(yarn cache dir)"
+      - name: Wat 2
+        run: git diff --name-only 619ef5978c3fbfa7c9d6a65c835e1e87dbcec55e '**/package.json'
 
-      - name: cache global yarn cache
-        uses: actions/cache@v2
-        if: steps.cache-modules.outputs.cache-hit != 'true'
-        with:
-          path: ${{ steps.yarn-cache.outputs.dir }}
-          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
-          restore-keys: |
-            ${{ runner.os }}-yarn-
+      - name: Wat 3
+        run: git diff --name-only 619ef5978c3fbfa7c9d6a65c835e1e87dbcec55e packages/integration/package.json
 
-      - name: yarn install
-        if: steps.cache-modules.outputs.cache-hit != 'true'
-        run: yarn install --frozen-lockfile
-      # End of yarn setup
+      - name: Wat 4
+        run: git diff --name-only 619ef5978c3fbfa7c9d6a65c835e1e87dbcec55e
 
-      - name: check for yarn.lock changes
-        id: yarn-lock
-        run: git diff --quiet origin/master HEAD -- yarn.lock
-        continue-on-error: true
+      - name: Check if release
+        id: release_check
+        run: node scripts/check-if-release.js
 
-      - name: verify doc links
-        run: node scripts/verify-links.js
+      # # Beginning of yarn setup, keep in sync between all workflows.
+      # # TODO(Rugvip): move this to composite action once all features we use are supported
+      # - name: use node.js ${{ matrix.node-version }}
+      #   uses: actions/setup-node@v1
+      #   with:
+      #     node-version: ${{ matrix.node-version }}
+      #     registry-url: https://registry.npmjs.org/ # Needed for auth
 
-      - name: prettier
-        run: yarn prettier:check
+      # # Cache every node_modules folder inside the monorepo
+      # - name: cache all node_modules
+      #   id: cache-modules
+      #   uses: actions/cache@v2
+      #   with:
+      #     path: '**/node_modules'
+      #     # We use both yarn.lock and package.json as cache keys to ensure that
+      #     # changes to local monorepo packages bust the cache.
+      #     key: ${{ runner.os }}-v${{ matrix.node-version }}-node_modules-${{ hashFiles('yarn.lock', '**/package.json') }}
 
-      - name: validate config
-        run: yarn backstage-cli config:check
+      # # If we get a cache hit for node_modules, there's no need to bring in the global
+      # # yarn cache or run yarn install, as all dependencies will be installed already.
 
-      - name: lint
-        run: yarn lerna -- run lint --since origin/master
+      # - name: find location of global yarn cache
+      #   id: yarn-cache
+      #   if: steps.cache-modules.outputs.cache-hit != 'true'
+      #   run: echo "::set-output name=dir::$(yarn cache dir)"
 
-      - name: type checking and declarations
-        run: yarn tsc:full
+      # - name: cache global yarn cache
+      #   uses: actions/cache@v2
+      #   if: steps.cache-modules.outputs.cache-hit != 'true'
+      #   with:
+      #     path: ${{ steps.yarn-cache.outputs.dir }}
+      #     key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
+      #     restore-keys: |
+      #       ${{ runner.os }}-yarn-
 
-      - name: build changed packages
-        if: ${{ steps.yarn-lock.outcome == 'success' }}
-        run: yarn lerna -- run build --since origin/master
+      # - name: yarn install
+      #   if: steps.cache-modules.outputs.cache-hit != 'true'
+      #   run: yarn install --frozen-lockfile
+      # # End of yarn setup
 
-      - name: build all packages
-        if: ${{ steps.yarn-lock.outcome == 'failure' }}
-        run: yarn lerna -- run build
+      # - name: check for yarn.lock changes
+      #   id: yarn-lock
+      #   run: git diff --quiet origin/master HEAD -- yarn.lock
+      #   continue-on-error: true
 
-      - name: verify type dependencies
-        run: yarn lint:type-deps
+      # - name: verify doc links
+      #   run: node scripts/verify-links.js
 
-      - name: test changed packages
-        if: ${{ steps.yarn-lock.outcome == 'success' }}
-        run: yarn lerna -- run test --since origin/master -- --coverage
+      # - name: prettier
+      #   run: yarn prettier:check
 
-      - name: test all packages (and upload coverage)
-        if: ${{ steps.yarn-lock.outcome == 'failure' }}
-        run: |
-          yarn lerna -- run test -- --coverage
-          bash <(curl -s https://codecov.io/bash) -N $(git rev-parse FETCH_HEAD)
+      # - name: validate config
+      #   run: yarn backstage-cli config:check
 
-      - name: verify plugin template
-        run: yarn lerna -- run diff -- --check
+      # - name: lint
+      #   run: yarn lerna -- run lint --since origin/master
 
-      - name: ensure clean working directory
-        run: |
-          if files=$(git ls-files --exclude-standard --others --modified) && [[ -z "$files" ]]; then
-            exit 0
-          else
-            echo ""
-            echo "Working directory has been modified:"
-            echo ""
-            git status --short
-            echo ""
-            exit 1
-          fi
+      # - name: type checking and declarations
+      #   run: yarn tsc:full
+
+      # - name: build changed packages
+      #   if: ${{ steps.yarn-lock.outcome == 'success' }}
+      #   run: yarn lerna -- run build --since origin/master
+
+      # - name: build all packages
+      #   if: ${{ steps.yarn-lock.outcome == 'failure' }}
+      #   run: yarn lerna -- run build
+
+      # - name: verify type dependencies
+      #   run: yarn lint:type-deps
+
+      # - name: test changed packages
+      #   if: ${{ steps.yarn-lock.outcome == 'success' }}
+      #   run: yarn lerna -- run test --since origin/master -- --coverage
+
+      # - name: test all packages (and upload coverage)
+      #   if: ${{ steps.yarn-lock.outcome == 'failure' }}
+      #   run: |
+      #     yarn lerna -- run test -- --coverage
+      #     bash <(curl -s https://codecov.io/bash) -N $(git rev-parse FETCH_HEAD)
+
+      # - name: verify plugin template
+      #   run: yarn lerna -- run diff -- --check
+
+      # - name: ensure clean working directory
+      #   run: |
+      #     if files=$(git ls-files --exclude-standard --others --modified) && [[ -z "$files" ]]; then
+      #       exit 0
+      #     else
+      #       echo ""
+      #       echo "Working directory has been modified:"
+      #       echo ""
+      #       git status --short
+      #       echo ""
+      #       exit 1
+      #     fi
+
+  release:
+    needs: verify
+
+    if: needs.verify.outputs.needs_release == 'true'
+
+    runs-on: ubuntu-latest
+
+    strategy:
+      matrix:
+        node-version: [12.x, 14.x]
+
+    steps:
+      - name: Hello
+        run: echo hello
